### ISSUE TITLE
Installing plugin along side vim-coloresque adds -,#,. to keywords

### ISSUE THREAD

**Issue by corevo** [styled-components/vim-styled-components#38]
Having both this plugin and coloresque adds the -,#,. to iskeyword,  
Its especially annoying when I try `ciw` and it picks up `something.foo` instead of just `foo`.  
```vim
Plugin 'gorodinskiy/vim-coloresque'
Plugin 'styled-components/vim-styled-components'
```
I tried swapping their order, as well as only loading them with minimal .vimrc containing only syntax enable and vundle.  
Both of them don't directly call `set iskeyword` which is why I'm a bit lost.

**Comment by fleischie** [comment]
Oh hi. This sounds like an interesting issue.

I will have to look into that. Gimme a half week or so. 😉

**Comment by fleischie** [comment]
@corevo Looking at the source, yes, `Plugin 'gko/vim-coloresque'` is setting keywords here: [after/syntax/css/vim-coloresque.vim#L125](https://github.com/gko/vim-coloresque/blob/0c21b1469993e610600e88e734ffe90b9c10a514/after/syntax/css/vim-coloresque.vim#L125).

So, yeah. The added keyword-characters are because of `vim-coloresque`.
