### ISSUE TITLE
Only load in files that contain styled components

### ISSUE THREAD

**Issue by snoblenet** [styled-components/vim-styled-components#59]
Is there some way to make this only load in files that actually import the styled components module?

Or at least only to `.jsx` files?

**Comment by fleischie** [comment]
Hello @snoblenet 

erm. The former was the implementation method used in v1 of this plugin, this was unstable and inefficient because of different import syntaxes and also you would have had to scan the opened file for these strings which could have slowed down startup times immensely.

Might I ask what your intentions are? Maybe there is a way but it is linked to what you are trying to achieve (and maybe also what kind of plugin manager you use (e.g. [vim-plug](https://github.com/junegunn/vim-plug#plug-options) allows you to specifiy the filetype you want to enable the plugin for via the `for` keyword, etc.)).

**Comment by snoblenet** [comment]
Thanks. My use case was that I was experiencing unreliable automatic indentation and the sheer number of plug-ins potentially making decisions in this area was making it hard to debug. Hence I wanted to disable plug-ins that may have a view about indentation but were not required in a given file.
